aliases:
  - &workspace_dir    /home/circleci/purposeindustries/content-editor
  - &step_attach_workspace
    attach_workspace:
      at: /home/circleci/purposeindustries/content-editor

defaults: &defaults
  working_directory:     /home/circleci/purposeindustries/content-editor
  parallelism: 1
  shell: /bin/bash --login

  environment:
    E2E_OUTPUT: $CIRCLE_TEST_REPORTS/e2e/
    E2E_SCREENSHOTS: $CIRCLE_ARTIFACTS/screenshots/
    E2E_ERRORSHOTS_OUTPUT: $CIRCLE_ARTIFACTS/e2e-errorshots/
    E2EPROFILE: sauceextended
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build-environment:
    <<: *defaults
    steps:
      - checkout
      - *step_attach_workspace
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/purposeindustries/content-editor
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - restore_cache:
          keys:
            - dependency-cache
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: echo -e "$NPMRC" >>$HOME/.npmrc

      - run: npm i --prefer-offline

      - save_cache:
          key: dependency-cache
          paths:
          - ~/.npm
          - ./node_modules

      - run:
          name: install system wide tools
          command: sudo apt-get install tree

      - persist_to_workspace:
          root: /home/circleci/purposeindustries/content-editor
          paths: .
  test:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: test
          command: npm run test
      - restore_cache:
          keys:
            - gatsby-cache

      - run:
          name: build assets
          command: npm run build
          environment:
            NODE_ENV: production
      - save_cache:
          key: gatsby-cache
          paths:
          - ./.cache

      - run:
          name: e2e test
          command: |
            set +e
            if [[ $CIRCLE_BRANCH != *"master"* || ! -z $CIRCLE_TAG ]] ; then
              E2EPROFILE=saucelight npm run test:e2e
            else
              npm run test:e2e
            fi
  reporting:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

  release:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Create new release
          command: |
            if [ -n "$RELEASE_TYPE" ]; then
              git config --global user.email "dev@purposeindustries.co"
              git config --global user.name "purpose-bot"
              npm version $RELEASE_TYPE
              git push
              git push --tags
            else
              echo "No RELEASE_TYPE is present, skipping creating new release."
            fi

  publish:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Publish new version to npm
          command: |
            npm publish
  deploy:
    <<: *defaults
    steps:
      - *step_attach_workspace
      - run:
          name: Deploy the version
          command: |
            npm run deploy
workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build-environment
      - test:
          requires:
            - build-environment
      - reporting:
          requires:
            - test
      - release:
          requires:
            - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              # matches v1.2.3, or v9.0.0
              only: /^v[0-9]+(\.[0-9]+)*$/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              # matches v1.2.3-next, or v1.2.3-1
              only: /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)+(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/
