
defaults: &defaults
  working_directory: /home/circleci/purposeindustries/intellyo-application-design-system
  parallelism: 1
  shell: /bin/bash --login

  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    E2E_OUTPUT: /tmp/circleci-artifacts/e2e/
    E2E_SCREENSHOTS: /tmp/circleci-artifacts/screenshots/
    E2E_ERRORSHOTS_OUTPUT: /tmp/circleci-test-results/e2e-errorshots/
    E2EPROFILE: saucelight
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - save_cache:
          key: v1-repo-{{ checksum "package.json" }}
          paths:
            - ~/purposeindustries/intellyo-application-design-system

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - v1-repo-{{ checksum "package.json" }}

      - run: echo -e "$NPMRC" >>$HOME/.npmrc

      - run: npm i --prefer-offline

      - run:
          name: install system wide tools
          command: sudo apt-get install tree

      - run:
          name: test
          command: npm run test

      - run:
          name: build assets
          command: npm run build
          environment:
            NODE_ENV: production

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ~/.npm
          - ./node_modules
          - ./.cache

      - run:
          name: e2e test
          command: |
            set +e
            E2EPROFILE=sauceextended npm run test:e2e -- --spec e2e/test/modal-tests/modal-test.js
            STATUS=$?;
            if [[ ! -z $FORCE_BUILD ]] ; then
              echo "The force build is active! Independently of the tests exit code the build does not fail. The exit code: $STATUS"
              exit 0
            else
              exit $STATUS
            fi

      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

      - run:
          name: Create new release
          command: |
            if [ -n "$RELEASE_TYPE" ]; then
              git config --global user.email "dev@purposeindustries.co"
              git config --global user.name "purpose-bot"
              git config --global push.default simple
              npm version $RELEASE_TYPE --commit-hooks=false
              git push -u origin $CIRCLE_BRANCH
              git push --tags
              npm run changelog
              git add CHANGELOG.md
              VERSION=$(npm view @pi/intellyo-components version -s)
              git commit -m "rls($VERSION): changelog updated"
              git push -f -u origin master
            else
              echo "No RELEASE_TYPE is present, skipping creating new release."
            fi
      - run:
          name: Publish new version to npm
          command: |
            # matches v1.2.3-next, or v1.2.3-1
            if [[ "$CIRCLE_TAG" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)+(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
              npm publish
            else
              echo "We are not building a tag or the tag is not a valid semver ($CIRCLE_TAG)";
            fi

      - run:
          name: Deploy the version
          command: |
            if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+)*$ ]]; then
              npm publish
              npm run deploy
            else
              echo "We are not building a tag, or the tag is not major, minor or patch but preversion ($CIRCLE_TAG)"
            fi

  #Duplicated code. Not possible to solve with yaml references on circleci
  nightly_build:
    <<: *defaults
    steps:
      - checkout

      - save_cache:
          key: v1-repo-{{ checksum "package.json" }}
          paths:
            - ~/purposeindustries/intellyo-application-design-system

      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - v1-repo-{{ checksum "package.json" }}

      - run: echo -e "$NPMRC" >>$HOME/.npmrc

      - run: npm i --prefer-offline

      - run:
          name: install system wide tools
          command: sudo apt-get install tree

      - run:
          name: test
          command: npm run test

      - run:
          name: build assets
          command: npm run build
          environment:
            NODE_ENV: production

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - ~/.npm
          - ./node_modules
          - ./.cache

      - run:
          name: e2e test
          command: E2EPROFILE=nightly npm run test:e2e

      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
  nightly_build:
    triggers:
      - schedule:
          cron: "00 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - nightly_build
